default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DBHOST'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  <<: *default
  database: coaching-api-development

test:
  <<: *default
  database: coaching-api-test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
